"""Compare streamline-field estimators head-to-head with held-out cross-validation.

Three regularizers turn the same binned per-cell tangents into a full field:

  diffusion    - precision-weighted diffusion of the two tangent components (shipped).
  laplace-fit  - fit a scalar depth potential with a data term in every cell; curl-free.
  laplace-bc   - pure Laplace interior with only the deep boundary as an empirical
                 condition and a flat shallow face (the parsimonious, boundary-driven
                 model).

For each held-out path it reports the in-band lateral deviation of each method's
predicted streamline (anchored at the path root), and -- the question this script exists
to answer -- how close ``laplace-bc`` lands to ``laplace-fit`` (if they nearly coincide,
the interior data adds little and the parsimonious boundary model suffices). It also
reports each full-data field's curl and divergence, the structural properties the PDE
methods are meant to control.

Run on real per-neuron .npy paths (nm, tip->root), matching build_streamline_field.py:

    uv run python scripts/compare_field_methods.py --paths /path/to/apical --dataset v1dd

or generate reproducible synthetic paths to sanity-check the machinery:

    uv run python scripts/compare_field_methods.py --synthetic 400 --dataset v1dd
"""

import argparse
import glob
import os
import time

import numpy as np

from standard_transform import streamline_field_from_paths
from standard_transform.datasets import minnie_transform, v1dd_transform

TRANSFORMS = {"v1dd": v1dd_transform, "minnie": minnie_transform}
DEFAULT_BANDS = {"v1dd": (150.0, 700.0), "minnie": (150.0, 650.0)}
DEFAULT_BIN = (30.0, 20.0, 30.0)
METHODS = ("diffusion", "laplace-fit", "laplace-bc")


def load_paths(directory):
    files = sorted(glob.glob(os.path.join(directory, "*.npy")))
    if not files:
        raise SystemExit(f"No .npy files found in {directory}")
    return [np.load(f)[:, :3].astype(float) for f in files]


def synthetic_paths(n, tform, seed=0):
    """Paths that all follow one *curl-free* ground-truth field, so the comparison is
    fair to the integrable (Laplace) methods. The field's tangent varies with lateral
    position and depth (boundary-explained curvature) and carries a mid-depth bump that
    the two boundaries do not imply -- the interior structure that ``laplace-bc`` must
    miss and ``laplace-fit``/``diffusion`` can capture. Paths are generated by
    integrating the field from a random root, then noised."""
    rng = np.random.default_rng(seed)
    yg = np.linspace(80.0, 760.0, 140)  # shallow (root) -> deep (tip)

    def tx(x, y):  # curl-free: t_x has no z-dependence, t_z (below) has no x-dependence
        return 0.12 + 2.5e-4 * x * (y / 1000.0) + 0.09 * np.exp(-((y - 450.0) / 90.0) ** 2)

    def tz(y):
        return 0.04 + 0.05 * (y / 1000.0)

    out = []
    for _ in range(n):
        x, z = rng.uniform(-220, 220), rng.uniform(-220, 220)
        xs, zs = [x], [z]
        for j in range(1, len(yg)):
            dy = yg[j] - yg[j - 1]
            x, z = x + tx(x, yg[j - 1]) * dy, z + tz(yg[j - 1]) * dy
            xs.append(x)
            zs.append(z)
        xs = np.array(xs) + rng.normal(0, 2.5, len(xs))
        zs = np.array(zs) + rng.normal(0, 2.5, len(zs))
        oriented = np.column_stack([xs, yg, zs])[::-1]  # reorder tip -> root
        out.append(tform.invert(oriented))
    return out


def build(train_oriented, tform, method, bin_size, depth_band, laplace_strength=0.05):
    # paths already oriented -> transform_points=False; tform attached for the field.
    return streamline_field_from_paths(
        train_oriented,
        tform=tform,
        transform_points=False,
        method=method,
        bin_size=tuple(bin_size),
        depth_band=tuple(depth_band),
        laplace_strength=laplace_strength,
    )


def predict(field, pp, band):
    lo, hi = band
    m = (pp[:, 1] >= lo) & (pp[:, 1] <= hi)
    if m.sum() < 2:
        return None
    fx, fz = field.streamline_at(pp[-1], pp[m, 1])  # anchor at root
    return pp[m, 0], pp[m, 2], np.asarray(fx), np.asarray(fz)


def field_curl_div(field):
    """Mean |curl| and |divergence| of the tangent field over interior in-band nodes."""
    t = field._tangents
    hx = float(np.median(np.diff(field._x_grid)))
    hz = float(np.median(np.diff(field._z_grid)))
    curl = np.gradient(t[..., 0], hz, axis=2) - np.gradient(t[..., 1], hx, axis=0)
    div = np.gradient(t[..., 0], hx, axis=0) + np.gradient(t[..., 1], hz, axis=2)
    sl = (slice(1, -1),) * 3
    return float(np.abs(curl[sl]).mean()), float(np.abs(div[sl]).mean())


def kfold(n, folds, seed):
    return np.array_split(np.random.default_rng(seed).permutation(n), folds)


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--paths", help="directory of per-neuron .npy files (nm)")
    ap.add_argument("--synthetic", type=int, metavar="N", help="use N synthetic paths instead")
    ap.add_argument("--dataset", required=True, choices=sorted(TRANSFORMS))
    ap.add_argument("--out", help="output .npz (default: compare_<dataset>.npz)")
    ap.add_argument("--folds", type=int, default=5)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--laplace-strength", type=float, default=0.05)
    ap.add_argument("--bin-size", type=float, nargs=3, default=DEFAULT_BIN, metavar=("X", "Y", "Z"))
    ap.add_argument("--depth-band", type=float, nargs=2, default=None, metavar=("LO", "HI"))
    args = ap.parse_args()

    if not args.paths and not args.synthetic:
        raise SystemExit("provide --paths DIR or --synthetic N")
    band = tuple(args.depth_band) if args.depth_band else DEFAULT_BANDS[args.dataset]
    tform = TRANSFORMS[args.dataset]()
    out = args.out or f"compare_{args.dataset}.npz"

    if args.synthetic:
        paths = synthetic_paths(args.synthetic, tform, args.seed)
        print(f"generated {len(paths)} synthetic paths")
    else:
        paths = load_paths(args.paths)
        print(f"loaded {len(paths)} paths from {args.paths}")
    oriented = [tform.apply(p) for p in paths]

    # per-path median deviation per method; per-point predictions per method (for agreement)
    devs = {m: [] for m in METHODS}
    preds = {m: {"x": [], "z": []} for m in METHODS}  # aligned across methods per point

    t0 = time.time()
    for fi, test_idx in enumerate(kfold(len(paths), args.folds, args.seed)):
        test = set(test_idx.tolist())
        train = [oriented[i] for i in range(len(paths)) if i not in test]
        fields = {m: build(train, tform, m, args.bin_size, band, args.laplace_strength) for m in METHODS}
        for i in test_idx:
            res = {m: predict(fields[m], oriented[i], band) for m in METHODS}
            if any(r is None for r in res.values()):
                continue
            for m in METHODS:
                ax, az, fx, fz = res[m]
                devs[m].append(float(np.median(np.sqrt((fx - ax) ** 2 + (fz - az) ** 2))))
                preds[m]["x"].append(fx)
                preds[m]["z"].append(fz)
        print(f"  fold {fi + 1}/{args.folds} done")

    for m in METHODS:
        for k in ("x", "z"):
            preds[m][k] = np.concatenate(preds[m][k])
    devs = {m: np.asarray(v) for m, v in devs.items()}

    # agreement: per-point lateral distance between method predictions (same anchor+depth)
    def agree(a, b):
        d = np.sqrt((preds[a]["x"] - preds[b]["x"]) ** 2 + (preds[a]["z"] - preds[b]["z"]) ** 2)
        return float(np.median(d)), float(np.percentile(d, 90))

    # structural metrics from full-data fields
    full = {m: build(oriented, tform, m, args.bin_size, band, args.laplace_strength) for m in METHODS}
    struct = {m: field_curl_div(full[m]) for m in METHODS}

    print(f"\ncross-validated {len(devs['diffusion'])} paths in {time.time() - t0:.1f}s\n")
    print(f"{'method':<13} {'median dev':>11} {'90th dev':>10} {'|curl|':>10} {'|div|':>10}")
    for m in METHODS:
        print(f"{m:<13} {np.median(devs[m]):>10.2f}u {np.percentile(devs[m], 90):>9.2f}u "
              f"{struct[m][0]:>10.2e} {struct[m][1]:>10.2e}")
    bc_fit = agree("laplace-bc", "laplace-fit")
    fit_diff = agree("laplace-fit", "diffusion")
    print(f"\nprediction agreement (median / 90th lateral distance between methods):")
    print(f"  laplace-bc  vs laplace-fit : {bc_fit[0]:.2f}u / {bc_fit[1]:.2f}u")
    print(f"  laplace-fit vs diffusion   : {fit_diff[0]:.2f}u / {fit_diff[1]:.2f}u")

    np.savez_compressed(
        out,
        methods=np.array(METHODS),
        **{f"dev_{m}": devs[m] for m in METHODS},
        **{f"predx_{m}": preds[m]["x"] for m in METHODS},
        **{f"predz_{m}": preds[m]["z"] for m in METHODS},
        curl=np.array([struct[m][0] for m in METHODS]),
        div=np.array([struct[m][1] for m in METHODS]),
        meta_dataset=np.array(args.dataset),
        meta_band=np.asarray(band),
        meta_bin=np.asarray(args.bin_size),
    )
    print(f"\nsaved -> {out}")


if __name__ == "__main__":
    main()
